# Generated by Django 5.2.4 on 2025-08-29 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='action',
            field=models.BooleanField(),
        ),
    ]
