# Generated by Django 5.2.4 on 2025-08-29 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_task_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='icon',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
